package enumerations;

public enum BaseDeDonnees {
	RECUP_TACHES_PREVUES, RECUP_TACHES_EN_COURS, RECUP_TACHES_TERMINEES, RECUP_RESS_HUM, RECUP_RESS_MAT, RECUP_RESS_LOG, RECUP_JALONS, RECUP_DATE_FIN_INITIALE, RECUP_DATE_FIN_FINALE, VERIF_PROJET, RECUP_SS_PROJETS;
}
